asset_path: /home/qiayuanl/Project/cal_hum_description/urdf/robot.urdf
usd_dir: /home/qiayuanl/Project/isaac/exts.berkeley_humanoid/exts/berkeley_humanoid/assets/Robots
usd_file_name: berkeley_humanoid.usd
force_usd_conversion: true
make_instanceable: true
import_inertia_tensor: true
fix_base: false
merge_fixed_joints: true
self_collision: false
default_drive_type: none
override_joint_dynamics: false
default_drive_stiffness: 0.0
default_drive_damping: 0.0
link_density: 0.0
convex_decompose_mesh: false